const stopsByLine = {
  "1": [
    "103 St",
    "116 St-Columbia University",
    "125 St",
    "137 St-City College",
    "14 St",
    "145 St",
    "157 St",
    "168 St-Washington Hts",
    "18 St",
    "181 St",
    "191 St",
    "207 St",
    "215 St",
    "23 St",
    "231 St",
    "238 St",
    "28 St",
    "34 St-Penn Station",
    "50 St",
    "59 St-Columbus Circle",
    "66 St-Lincoln Center",
    "72 St",
    "79 St",
    "86 St",
    "96 St",
    "Canal St",
    "Cathedral Pkwy (110 St)",
    "Chambers St",
    "Christopher St-Stonewall",
    "Dyckman St",
    "Franklin St",
    "Houston St",
    "Marble Hill-225 St",
    "Rector St",
    "South Ferry",
    "Times Sq-42 St",
    "Van Cortlandt Park-242 St",
    "WTC Cortlandt"
  ],
  "2": [
    "116 St",
    "125 St",
    "135 St",
    "14 St",
    "149 St-Grand Concourse",
    "174 St",
    "219 St",
    "225 St",
    "233 St",
    "3 Ave-149 St",
    "34 St-Penn Station",
    "72 St",
    "96 St",
    "Allerton Ave",
    "Atlantic Ave-Barclays Ctr",
    "Bergen St",
    "Beverly Rd",
    "Borough Hall",
    "Bronx Park East",
    "Burke Ave",
    "Central Park North (110 St)",
    "Chambers St",
    "Church Ave",
    "Clark St",
    "E 180 St",
    "Eastern Pkwy-Brooklyn Museum",
    "Flatbush Ave-Brooklyn College",
    "Franklin Ave-Medgar Evers College",
    "Freeman St",
    "Fulton St",
    "Grand Army Plaza",
    "Gun Hill Rd",
    "Hoyt St",
    "Intervale Ave",
    "Jackson Ave",
    "Nereid Ave",
    "Nevins St",
    "Newkirk Ave-Little Haiti",
    "Park Place",
    "Pelham Pkwy",
    "President St-Medgar Evers College",
    "Prospect Ave",
    "Simpson St",
    "Sterling St",
    "Times Sq-42 St",
    "Wakefield-241 St",
    "Wall St",
    "West Farms Sq-E Tremont Ave",
    "Winthrop St"
  ],
  "3": [
    "116 St",
    "125 St",
    "135 St",
    "14 St",
    "145 St",
    "34 St-Penn Station",
    "72 St",
    "96 St",
    "Atlantic Ave-Barclays Ctr",
    "Bergen St",
    "Borough Hall",
    "Central Park North (110 St)",
    "Chambers St",
    "Clark St",
    "Crown Hts-Utica Ave",
    "Eastern Pkwy-Brooklyn Museum",
    "Franklin Ave-Medgar Evers College",
    "Fulton St",
    "Grand Army Plaza",
    "Harlem-148 St",
    "Hoyt St",
    "Junius St",
    "Kingston Ave",
    "Nevins St",
    "New Lots Ave",
    "Nostrand Ave",
    "Park Place",
    "Pennsylvania Ave",
    "Rockaway Ave",
    "Saratoga Ave",
    "Sutter Ave-Rutland Rd",
    "Times Sq-42 St",
    "Van Siclen Ave",
    "Wall St"
  ],
  "SIR": [
    "Annadale",
    "Arthur Kill",
    "Bay Terrace",
    "Clifton",
    "Dongan Hills",
    "Eltingville",
    "Grant City",
    "Grasmere",
    "Great Kills",
    "Huguenot",
    "Jefferson Ave",
    "New Dorp",
    "Oakwood Heights",
    "Old Town",
    "Pleasant Plains",
    "Prince's Bay",
    "Richmond Valley",
    "St George",
    "Stapleton",
    "Tompkinsville",
    "Tottenville"
  ],
  "S": [
    "Beach 105 St",
    "Beach 90 St",
    "Beach 98 St",
    "Botanic Garden",
    "Broad Channel",
    "Franklin Ave",
    "Grand Central-42 St",
    "Park Pl",
    "Prospect Park",
    "Rockaway Park-Beach 116 St",
    "Times Sq-42 St"
  ],
  "M": [
    "14 St",
    "23 St",
    "34 St-Herald Sq",
    "36 St",
    "42 St-Bryant Pk",
    "46 St",
    "47-50 Sts-Rockefeller Ctr",
    "5 Ave/53 St",
    "63 Dr-Rego Park",
    "65 St",
    "67 Ave",
    "Broadway-Lafayette St",
    "Central Ave",
    "Court Sq-23 St",
    "Delancey St-Essex St",
    "Elmhurst Ave",
    "Flushing Ave",
    "Forest Ave",
    "Forest Hills-71 Ave",
    "Fresh Pond Rd",
    "Grand Ave-Newtown",
    "Hewes St",
    "Jackson Hts-Roosevelt Ave",
    "Knickerbocker Ave",
    "Lexington Ave/53 St",
    "Lorimer St",
    "Marcy Ave",
    "Middle Village-Metropolitan Ave",
    "Myrtle Ave",
    "Myrtle-Wyckoff Aves",
    "Northern Blvd",
    "Queens Plaza",
    "Seneca Ave",
    "Steinway St",
    "W 4 St-Wash Sq",
    "WoodhAveen Blvd"
  ],
  "7": [
    "103 St-Corona Plaza",
    "111 St",
    "33 St-Rawson St",
    "34 St-Hudson Yards",
    "40 St-Lowery St",
    "46 St-Bliss St",
    "5 Ave",
    "52 St",
    "61 St-Woodside",
    "69 St",
    "74 St-Broadway",
    "82 St-Jackson Hts",
    "90 St-Elmhurst Ave",
    "Court Sq",
    "Flushing-Main St",
    "Grand Central-42 St",
    "Hunters Point Ave",
    "Junction Blvd",
    "Mets-Willets Point",
    "Queensboro Plaza",
    "Times Sq-42 St",
    "Vernon Blvd-Jackson Ave"
  ],
  "6": [
    "103 St",
    "110 St",
    "116 St",
    "125 St",
    "14 St-Union Sq",
    "23 St",
    "28 St",
    "3 Ave-138 St",
    "33 St",
    "51 St",
    "59 St",
    "68 St-Hunter College",
    "77 St",
    "86 St",
    "96 St",
    "Astor Pl",
    "Bleecker St",
    "Brook Ave",
    "Brooklyn Bridge-City Hall",
    "Buhre Ave",
    "Canal St",
    "Castle Hill Ave",
    "Cypress Ave",
    "E 143 St-St Mary's St",
    "E 149 St",
    "Elder Ave",
    "Grand Central-42 St",
    "Hunts Point Ave",
    "Longwood Ave",
    "Middletown Rd",
    "Morrison Ave-Soundview",
    "Parkchester",
    "Pelham Bay Park",
    "Spring St",
    "St Lawrence Ave",
    "Westchester Sq-E Tremont Ave",
    "Whitlock Ave",
    "Zerega Ave"
  ],
  "J": [
    "104 St",
    "111 St",
    "121 St",
    "75 St-Elderts Ln",
    "85 St-Forest Pkwy",
    "Alabama Ave",
    "Bowery",
    "Broad St",
    "Broadway Junction",
    "Canal St",
    "Chambers St",
    "Chauncey St",
    "Cleveland St",
    "Crescent St",
    "Cypress Hills",
    "Delancey St-Essex St",
    "Flushing Ave",
    "Fulton St",
    "Gates Ave",
    "Halsey St",
    "Hewes St",
    "Jamaica Center-Parsons/Archer",
    "Kosciuszko St",
    "Lorimer St",
    "Marcy Ave",
    "Myrtle Ave",
    "Norwood Ave",
    "Sutphin Blvd-Archer Ave-JFK Airport",
    "Van Siclen Ave",
    "WoodhAveen Blvd"
  ],
  "Z": [
    "104 St",
    "121 St",
    "75 St-Elderts Ln",
    "Alabama Ave",
    "Bowery",
    "Broad St",
    "Broadway Junction",
    "Canal St",
    "Chambers St",
    "Chauncey St",
    "Crescent St",
    "Delancey St-Essex St",
    "Fulton St",
    "Gates Ave",
    "Jamaica Center-Parsons/Archer",
    "Marcy Ave",
    "Myrtle Ave",
    "Norwood Ave",
    "Sutphin Blvd-Archer Ave-JFK Airport",
    "Van Siclen Ave",
    "WoodhAveen Blvd"
  ],
  "F": [
    "14 St",
    "15 St-Prospect Park",
    "169 St",
    "18 Ave",
    "2 Ave",
    "21 St-Queensbridge",
    "23 St",
    "34 St-Herald Sq",
    "4 Ave-9 St",
    "42 St-Bryant Pk",
    "47-50 Sts-Rockefeller Ctr",
    "57 St",
    "7 Ave",
    "75 Ave",
    "Aveenue I",
    "Aveenue N",
    "Aveenue P",
    "Aveenue U",
    "Aveenue X",
    "Bay Pkwy",
    "Bergen St",
    "Briarwood",
    "Broadway-Lafayette St",
    "Carroll St",
    "Church Ave",
    "Coney Island-Stillwell Ave",
    "Delancey St-Essex St",
    "Ditmas Ave",
    "East Broadway",
    "Forest Hills-71 Ave",
    "Fort Hamilton Pkwy",
    "Jackson Hts-Roosevelt Ave",
    "Jamaica-179 St",
    "Jay St-MetroTech",
    "Kew Gardens-Union Tpke",
    "Kings Hwy",
    "Lexington Ave/63 St",
    "Neptune Ave",
    "Parsons Blvd",
    "Roosevelt Island",
    "Smith-9 Sts",
    "Sutphin Blvd",
    "W 4 St-Wash Sq",
    "W 8 St-NY Aquarium",
    "York St"
  ],
  "R": [
    "14 St-Union Sq",
    "23 St",
    "25 St",
    "28 St",
    "34 St-Herald Sq",
    "36 St",
    "4 Ave-9 St",
    "45 St",
    "46 St",
    "49 St",
    "5 Ave/59 St",
    "53 St",
    "57 St-7 Ave",
    "59 St",
    "63 Dr-Rego Park",
    "65 St",
    "67 Ave",
    "77 St",
    "8 St-NYU",
    "86 St",
    "Atlantic Ave-Barclays Ctr",
    "Bay Ridge Ave",
    "Bay Ridge-95 St",
    "Canal St",
    "City Hall",
    "Cortlandt St",
    "Court St",
    "DeKalb Ave",
    "Elmhurst Ave",
    "Forest Hills-71 Ave",
    "Grand Ave-Newtown",
    "Jackson Hts-Roosevelt Ave",
    "Jay St-MetroTech",
    "Lexington Ave/59 St",
    "Northern Blvd",
    "Prince St",
    "Prospect Ave",
    "Queens Plaza",
    "Rector St",
    "Steinway St",
    "Times Sq-42 St",
    "Union St",
    "Whitehall St-South Ferry",
    "WoodhAveen Blvd"
  ],
  "A": [
    "104 St",
    "111 St",
    "125 St",
    "14 St",
    "145 St",
    "168 St",
    "175 St",
    "181 St",
    "190 St",
    "34 St-Penn Station",
    "42 St-Port Authority Bus Terminal",
    "59 St-Columbus Circle",
    "80 St",
    "88 St",
    "Aqueduct Racetrack",
    "Aqueduct-N Conduit Ave",
    "Beach 105 St",
    "Beach 25 St",
    "Beach 36 St",
    "Beach 44 St",
    "Beach 60 St",
    "Beach 67 St",
    "Beach 90 St",
    "Beach 98 St",
    "Broad Channel",
    "Broadway Junction",
    "Canal St",
    "Chambers St",
    "Dyckman St",
    "Euclid Ave",
    "Far Rockaway-Mott Ave",
    "Fulton St",
    "Grant Ave",
    "High St",
    "Howard Beach-JFK Airport",
    "Hoyt-Schermerhorn Sts",
    "Inwood-207 St",
    "Jay St-MetroTech",
    "Nostrand Ave",
    "Ozone Park-Lefferts Blvd",
    "Rockaway Blvd",
    "Rockaway Park-Beach 116 St",
    "Utica Ave",
    "W 4 St-Wash Sq"
  ],
  "C": [
    "103 St",
    "116 St",
    "125 St",
    "135 St",
    "14 St",
    "145 St",
    "155 St",
    "163 St-Amsterdam Ave",
    "168 St",
    "23 St",
    "34 St-Penn Station",
    "42 St-Port Authority Bus Terminal",
    "50 St",
    "59 St-Columbus Circle",
    "72 St",
    "81 St-Museum of Natural History",
    "86 St",
    "96 St",
    "Broadway Junction",
    "Canal St",
    "Cathedral Pkwy (110 St)",
    "Chambers St",
    "Clinton-Washington Aves",
    "Euclid Ave",
    "Franklin Ave",
    "Fulton St",
    "High St",
    "Hoyt-Schermerhorn Sts",
    "Jay St-MetroTech",
    "Kingston-Throop Aves",
    "Lafayette Ave",
    "Liberty Ave",
    "Nostrand Ave",
    "Ralph Ave",
    "Rockaway Ave",
    "Shepherd Ave",
    "Spring St",
    "Utica Ave",
    "Van Siclen Ave",
    "W 4 St-Wash Sq"
  ],
  "B": [
    "103 St",
    "116 St",
    "125 St",
    "135 St",
    "145 St",
    "155 St",
    "161 St-Yankee Stadium",
    "167 St",
    "170 St",
    "174-175 Sts",
    "182-183 Sts",
    "34 St-Herald Sq",
    "42 St-Bryant Pk",
    "47-50 Sts-Rockefeller Ctr",
    "59 St-Columbus Circle",
    "7 Ave",
    "72 St",
    "81 St-Museum of Natural History",
    "86 St",
    "96 St",
    "Atlantic Ave-Barclays Ctr",
    "Bedford Park Blvd",
    "Brighton Beach",
    "Broadway-Lafayette St",
    "Cathedral Pkwy (110 St)",
    "Church Ave",
    "DeKalb Ave",
    "Fordham Rd",
    "Grand St",
    "Kings Hwy",
    "Kingsbridge Rd",
    "Newkirk Plaza",
    "Prospect Park",
    "Sheepshead Bay",
    "Tremont Ave",
    "W 4 St-Wash Sq"
  ],
  "D": [
    "125 St",
    "145 St",
    "155 St",
    "161 St-Yankee Stadium",
    "167 St",
    "170 St",
    "174-175 Sts",
    "18 Ave",
    "182-183 Sts",
    "20 Ave",
    "25 Ave",
    "34 St-Herald Sq",
    "36 St",
    "42 St-Bryant Pk",
    "47-50 Sts-Rockefeller Ctr",
    "50 St",
    "55 St",
    "59 St-Columbus Circle",
    "62 St",
    "7 Ave",
    "71 St",
    "79 St",
    "9 Ave",
    "Atlantic Ave-Barclays Ctr",
    "Bay 50 St",
    "Bay Pkwy",
    "Bedford Park Blvd",
    "Broadway-Lafayette St",
    "Coney Island-Stillwell Ave",
    "Fordham Rd",
    "Fort Hamilton Pkwy",
    "Grand St",
    "Kingsbridge Rd",
    "Norwood-205 St",
    "Tremont Ave",
    "W 4 St-Wash Sq"
  ],
  "4": [
    "125 St",
    "138 St-Grand Concourse",
    "14 St-Union Sq",
    "149 St-Grand Concourse",
    "161 St-Yankee Stadium",
    "167 St",
    "170 St",
    "176 St",
    "183 St",
    "59 St",
    "86 St",
    "Atlantic Ave-Barclays Ctr",
    "Bedford Park Blvd-Lehman College",
    "Borough Hall",
    "Bowling Green",
    "Brooklyn Bridge-City Hall",
    "Burnside Ave",
    "Crown Hts-Utica Ave",
    "Fordham Rd",
    "Franklin Ave-Medgar Evers College",
    "Fulton St",
    "Grand Central-42 St",
    "Kingsbridge Rd",
    "Mosholu Pkwy",
    "Mt Eden Ave",
    "Nevins St",
    "Wall St",
    "Woodlawn"
  ],
  "5": [
    "125 St",
    "138 St-Grand Concourse",
    "14 St-Union Sq",
    "149 St-Grand Concourse",
    "174 St",
    "219 St",
    "225 St",
    "233 St",
    "3 Ave-149 St",
    "59 St",
    "86 St",
    "Allerton Ave",
    "Atlantic Ave-Barclays Ctr",
    "Baychester Ave",
    "Beverly Rd",
    "Borough Hall",
    "Bowling Green",
    "Bronx Park East",
    "Brooklyn Bridge-City Hall",
    "Burke Ave",
    "Church Ave",
    "E 180 St",
    "Eastchester-Dyre Ave",
    "Flatbush Ave-Brooklyn College",
    "Franklin Ave-Medgar Evers College",
    "Freeman St",
    "Fulton St",
    "Grand Central-42 St",
    "Gun Hill Rd",
    "Intervale Ave",
    "Jackson Ave",
    "Morris Park",
    "Nereid Ave",
    "Nevins St",
    "Newkirk Ave-Little Haiti",
    "Pelham Pkwy",
    "President St-Medgar Evers College",
    "Prospect Ave",
    "Simpson St",
    "Sterling St",
    "Wall St",
    "West Farms Sq-E Tremont Ave",
    "Winthrop St"
  ],
  "N": [
    "14 St-Union Sq",
    "18 Ave",
    "20 Ave",
    "30 Ave",
    "34 St-Herald Sq",
    "36 Ave",
    "36 St",
    "39 Ave-Dutch Kills",
    "49 St",
    "5 Ave/59 St",
    "57 St-7 Ave",
    "59 St",
    "8 Ave",
    "86 St",
    "Astoria Blvd",
    "Astoria-Ditmars Blvd",
    "Atlantic Ave-Barclays Ctr",
    "Aveenue U",
    "Bay Pkwy",
    "Broadway",
    "Canal St",
    "Coney Island-Stillwell Ave",
    "Fort Hamilton Pkwy",
    "Kings Hwy",
    "Lexington Ave/59 St",
    "New Utrecht Ave",
    "Queensboro Plaza",
    "Times Sq-42 St"
  ],
  "W": [
    "14 St-Union Sq",
    "23 St",
    "28 St",
    "30 Ave",
    "34 St-Herald Sq",
    "36 Ave",
    "39 Ave-Dutch Kills",
    "49 St",
    "5 Ave/59 St",
    "57 St-7 Ave",
    "8 St-NYU",
    "Astoria Blvd",
    "Astoria-Ditmars Blvd",
    "Broadway",
    "Canal St",
    "City Hall",
    "Cortlandt St",
    "Lexington Ave/59 St",
    "Prince St",
    "Queensboro Plaza",
    "Rector St",
    "Times Sq-42 St",
    "Whitehall St-South Ferry"
  ],
  "E": [
    "14 St",
    "23 St",
    "34 St-Penn Station",
    "42 St-Port Authority Bus Terminal",
    "5 Ave/53 St",
    "50 St",
    "7 Ave",
    "75 Ave",
    "Briarwood",
    "Canal St",
    "Court Sq-23 St",
    "Forest Hills-71 Ave",
    "Jackson Hts-Roosevelt Ave",
    "Jamaica Center-Parsons/Archer",
    "Jamaica-Van Wyck",
    "Kew Gardens-Union Tpke",
    "Lexington Ave/53 St",
    "Queens Plaza",
    "Spring St",
    "Sutphin Blvd-Archer Ave-JFK Airport",
    "W 4 St-Wash Sq",
    "World Trade Center"
  ],
  "G": [
    "15 St-Prospect Park",
    "21 St",
    "4 Ave-9 St",
    "7 Ave",
    "Bedford-Nostrand Aves",
    "Bergen St",
    "Broadway",
    "Carroll St",
    "Church Ave",
    "Classon Ave",
    "Clinton-Washington Aves",
    "Court Sq",
    "Flushing Ave",
    "Fort Hamilton Pkwy",
    "Fulton St",
    "Greenpoint Ave",
    "Hoyt-Schermerhorn Sts",
    "Metropolitan Ave",
    "Myrtle-Willoughby Aves",
    "Nassau Ave",
    "Smith-9 Sts"
  ],
  "Q": [
    "14 St-Union Sq",
    "34 St-Herald Sq",
    "57 St-7 Ave",
    "7 Ave",
    "72 St",
    "86 St",
    "96 St",
    "Atlantic Ave-Barclays Ctr",
    "Aveenue H",
    "Aveenue J",
    "Aveenue M",
    "Aveenue U",
    "Beverley Rd",
    "Brighton Beach",
    "Canal St",
    "Church Ave",
    "Coney Island-Stillwell Ave",
    "Cortelyou Rd",
    "DeKalb Ave",
    "Kings Hwy",
    "Lexington Ave/63 St",
    "Neck Rd",
    "Newkirk Plaza",
    "Ocean Pkwy",
    "Parkside Ave",
    "Prospect Park",
    "Sheepshead Bay",
    "Times Sq-42 St",
    "W 8 St-NY Aquarium"
  ],
  "L": [
    "1 Ave",
    "14 St-Union Sq",
    "3 Ave",
    "6 Ave",
    "8 Ave",
    "Atlantic Ave",
    "Bedford Ave",
    "Broadway Junction",
    "Bushwick Ave-Aberdeen St",
    "Canarsie-Rockaway Pkwy",
    "DeKalb Ave",
    "East 105 St",
    "Graham Ave",
    "Grand St",
    "Halsey St",
    "Jefferson St",
    "Livonia Ave",
    "Lorimer St",
    "Montrose Ave",
    "Morgan Ave",
    "Myrtle-Wyckoff Aves",
    "New Lots Ave",
    "Sutter Ave",
    "Wilson Ave"
  ]
};