const stopsByLine = {
  "1": [
    "103 St",
    "116 St-Columbia University",
    "125 St",
    "137 St-City College",
    "14 St",
    "145 St",
    "157 St",
    "168 St-Washington Hts",
    "18 St",
    "181 St",
    "191 St",
    "207 St",
    "215 St",
    "23 St",
    "231 St",
    "238 St",
    "28 St",
    "34 St-Penn Station",
    "50 St",
    "59 St-Columbus Circle",
    "66 St-Lincoln Center",
    "72 St",
    "79 St",
    "86 St",
    "96 St",
    "Canal St",
    "Cathedral Pkwy (110 St)",
    "Chambers St",
    "Christopher St-Stonewall",
    "Dyckman St",
    "Franklin St",
    "Houston St",
    "Marble Hill-225 St",
    "Rector St",
    "South Ferry",
    "Times Sq-42 St",
    "Van Cortlandt Park-242 St",
    "WTC Cortlandt"
  ],
  "2": [
    "116 St",
    "125 St",
    "135 St",
    "14 St",
    "149 St-Grand Concourse",
    "174 St",
    "219 St",
    "225 St",
    "233 St",
    "3 Av-149 St",
    "34 St-Penn Station",
    "72 St",
    "96 St",
    "Allerton Av",
    "Atlantic Av-Barclays Ctr",
    "Bergen St",
    "Beverly Rd",
    "Borough Hall",
    "Bronx Park East",
    "Burke Av",
    "Central Park North (110 St)",
    "Chambers St",
    "Church Av",
    "Clark St",
    "E 180 St",
    "Eastern Pkwy-Brooklyn Museum",
    "Flatbush Av-Brooklyn College",
    "Franklin Av-Medgar Evers College",
    "Freeman St",
    "Fulton St",
    "Grand Army Plaza",
    "Gun Hill Rd",
    "Hoyt St",
    "Intervale Av",
    "Jackson Av",
    "Nereid Av",
    "Nevins St",
    "Newkirk Av-Little Haiti",
    "Park Place",
    "Pelham Pkwy",
    "President St-Medgar Evers College",
    "Prospect Av",
    "Simpson St",
    "Sterling St",
    "Times Sq-42 St",
    "Wakefield-241 St",
    "Wall St",
    "West Farms Sq-E Tremont Av",
    "Winthrop St"
  ],
  "3": [
    "116 St",
    "125 St",
    "135 St",
    "14 St",
    "145 St",
    "34 St-Penn Station",
    "72 St",
    "96 St",
    "Atlantic Av-Barclays Ctr",
    "Bergen St",
    "Borough Hall",
    "Central Park North (110 St)",
    "Chambers St",
    "Clark St",
    "Crown Hts-Utica Av",
    "Eastern Pkwy-Brooklyn Museum",
    "Franklin Av-Medgar Evers College",
    "Fulton St",
    "Grand Army Plaza",
    "Harlem-148 St",
    "Hoyt St",
    "Junius St",
    "Kingston Av",
    "Nevins St",
    "New Lots Av",
    "Nostrand Av",
    "Park Place",
    "Pennsylvania Av",
    "Rockaway Av",
    "Saratoga Av",
    "Sutter Av-Rutland Rd",
    "Times Sq-42 St",
    "Van Siclen Av",
    "Wall St"
  ],
  "SIR": [
    "Annadale",
    "Arthur Kill",
    "Bay Terrace",
    "Clifton",
    "Dongan Hills",
    "Eltingville",
    "Grant City",
    "Grasmere",
    "Great Kills",
    "Huguenot",
    "Jefferson Av",
    "New Dorp",
    "Oakwood Heights",
    "Old Town",
    "Pleasant Plains",
    "Prince's Bay",
    "Richmond Valley",
    "St George",
    "Stapleton",
    "Tompkinsville",
    "Tottenville"
  ],
  "S": [
    "Beach 105 St",
    "Beach 90 St",
    "Beach 98 St",
    "Botanic Garden",
    "Broad Channel",
    "Franklin Av",
    "Grand Central-42 St",
    "Park Pl",
    "Prospect Park",
    "Rockaway Park-Beach 116 St",
    "Times Sq-42 St"
  ],
  "M": [
    "14 St",
    "23 St",
    "34 St-Herald Sq",
    "36 St",
    "42 St-Bryant Pk",
    "46 St",
    "47-50 Sts-Rockefeller Ctr",
    "5 Av/53 St",
    "63 Dr-Rego Park",
    "65 St",
    "67 Av",
    "Broadway-Lafayette St",
    "Central Av",
    "Court Sq-23 St",
    "Delancey St-Essex St",
    "Elmhurst Av",
    "Flushing Av",
    "Forest Av",
    "Forest Hills-71 Av",
    "Fresh Pond Rd",
    "Grand Av-Newtown",
    "Hewes St",
    "Jackson Hts-Roosevelt Av",
    "Knickerbocker Av",
    "Lexington Av/53 St",
    "Lorimer St",
    "Marcy Av",
    "Middle Village-Metropolitan Av",
    "Myrtle Av",
    "Myrtle-Wyckoff Avs",
    "Northern Blvd",
    "Queens Plaza",
    "Seneca Av",
    "Steinway St",
    "W 4 St-Wash Sq",
    "Woodhaven Blvd"
  ],
  "7": [
    "103 St-Corona Plaza",
    "111 St",
    "33 St-Rawson St",
    "34 St-Hudson Yards",
    "40 St-Lowery St",
    "46 St-Bliss St",
    "5 Av",
    "52 St",
    "61 St-Woodside",
    "69 St",
    "74 St-Broadway",
    "82 St-Jackson Hts",
    "90 St-Elmhurst Av",
    "Court Sq",
    "Flushing-Main St",
    "Grand Central-42 St",
    "Hunters Point Av",
    "Junction Blvd",
    "Mets-Willets Point",
    "Queensboro Plaza",
    "Times Sq-42 St",
    "Vernon Blvd-Jackson Av"
  ],
  "6": [
    "103 St",
    "110 St",
    "116 St",
    "125 St",
    "14 St-Union Sq",
    "23 St",
    "28 St",
    "3 Av-138 St",
    "33 St",
    "51 St",
    "59 St",
    "68 St-Hunter College",
    "77 St",
    "86 St",
    "96 St",
    "Astor Pl",
    "Bleecker St",
    "Brook Av",
    "Brooklyn Bridge-City Hall",
    "Buhre Av",
    "Canal St",
    "Castle Hill Av",
    "Cypress Av",
    "E 143 St-St Mary's St",
    "E 149 St",
    "Elder Av",
    "Grand Central-42 St",
    "Hunts Point Av",
    "Longwood Av",
    "Middletown Rd",
    "Morrison Av-Soundview",
    "Parkchester",
    "Pelham Bay Park",
    "Spring St",
    "St Lawrence Av",
    "Westchester Sq-E Tremont Av",
    "Whitlock Av",
    "Zerega Av"
  ],
  "J": [
    "104 St",
    "111 St",
    "121 St",
    "75 St-Elderts Ln",
    "85 St-Forest Pkwy",
    "Alabama Av",
    "Bowery",
    "Broad St",
    "Broadway Junction",
    "Canal St",
    "Chambers St",
    "Chauncey St",
    "Cleveland St",
    "Crescent St",
    "Cypress Hills",
    "Delancey St-Essex St",
    "Flushing Av",
    "Fulton St",
    "Gates Av",
    "Halsey St",
    "Hewes St",
    "Jamaica Center-Parsons/Archer",
    "Kosciuszko St",
    "Lorimer St",
    "Marcy Av",
    "Myrtle Av",
    "Norwood Av",
    "Sutphin Blvd-Archer Av-JFK Airport",
    "Van Siclen Av",
    "Woodhaven Blvd"
  ],
  "Z": [
    "104 St",
    "121 St",
    "75 St-Elderts Ln",
    "Alabama Av",
    "Bowery",
    "Broad St",
    "Broadway Junction",
    "Canal St",
    "Chambers St",
    "Chauncey St",
    "Crescent St",
    "Delancey St-Essex St",
    "Fulton St",
    "Gates Av",
    "Jamaica Center-Parsons/Archer",
    "Marcy Av",
    "Myrtle Av",
    "Norwood Av",
    "Sutphin Blvd-Archer Av-JFK Airport",
    "Van Siclen Av",
    "Woodhaven Blvd"
  ],
  "F": [
    "14 St",
    "15 St-Prospect Park",
    "169 St",
    "18 Av",
    "2 Av",
    "21 St-Queensbridge",
    "23 St",
    "34 St-Herald Sq",
    "4 Av-9 St",
    "42 St-Bryant Pk",
    "47-50 Sts-Rockefeller Ctr",
    "57 St",
    "7 Av",
    "75 Av",
    "Avenue I",
    "Avenue N",
    "Avenue P",
    "Avenue U",
    "Avenue X",
    "Bay Pkwy",
    "Bergen St",
    "Briarwood",
    "Broadway-Lafayette St",
    "Carroll St",
    "Church Av",
    "Coney Island-Stillwell Av",
    "Delancey St-Essex St",
    "Ditmas Av",
    "East Broadway",
    "Forest Hills-71 Av",
    "Fort Hamilton Pkwy",
    "Jackson Hts-Roosevelt Av",
    "Jamaica-179 St",
    "Jay St-MetroTech",
    "Kew Gardens-Union Tpke",
    "Kings Hwy",
    "Lexington Av/63 St",
    "Neptune Av",
    "Parsons Blvd",
    "Roosevelt Island",
    "Smith-9 Sts",
    "Sutphin Blvd",
    "W 4 St-Wash Sq",
    "W 8 St-NY Aquarium",
    "York St"
  ],
  "R": [
    "14 St-Union Sq",
    "23 St",
    "25 St",
    "28 St",
    "34 St-Herald Sq",
    "36 St",
    "4 Av-9 St",
    "45 St",
    "46 St",
    "49 St",
    "5 Av/59 St",
    "53 St",
    "57 St-7 Av",
    "59 St",
    "63 Dr-Rego Park",
    "65 St",
    "67 Av",
    "77 St",
    "8 St-NYU",
    "86 St",
    "Atlantic Av-Barclays Ctr",
    "Bay Ridge Av",
    "Bay Ridge-95 St",
    "Canal St",
    "City Hall",
    "Cortlandt St",
    "Court St",
    "DeKalb Av",
    "Elmhurst Av",
    "Forest Hills-71 Av",
    "Grand Av-Newtown",
    "Jackson Hts-Roosevelt Av",
    "Jay St-MetroTech",
    "Lexington Av/59 St",
    "Northern Blvd",
    "Prince St",
    "Prospect Av",
    "Queens Plaza",
    "Rector St",
    "Steinway St",
    "Times Sq-42 St",
    "Union St",
    "Whitehall St-South Ferry",
    "Woodhaven Blvd"
  ],
  "A": [
    "104 St",
    "111 St",
    "125 St",
    "14 St",
    "145 St",
    "168 St",
    "175 St",
    "181 St",
    "190 St",
    "34 St-Penn Station",
    "42 St-Port Authority Bus Terminal",
    "59 St-Columbus Circle",
    "80 St",
    "88 St",
    "Aqueduct Racetrack",
    "Aqueduct-N Conduit Av",
    "Beach 105 St",
    "Beach 25 St",
    "Beach 36 St",
    "Beach 44 St",
    "Beach 60 St",
    "Beach 67 St",
    "Beach 90 St",
    "Beach 98 St",
    "Broad Channel",
    "Broadway Junction",
    "Canal St",
    "Chambers St",
    "Dyckman St",
    "Euclid Av",
    "Far Rockaway-Mott Av",
    "Fulton St",
    "Grant Av",
    "High St",
    "Howard Beach-JFK Airport",
    "Hoyt-Schermerhorn Sts",
    "Inwood-207 St",
    "Jay St-MetroTech",
    "Nostrand Av",
    "Ozone Park-Lefferts Blvd",
    "Rockaway Blvd",
    "Rockaway Park-Beach 116 St",
    "Utica Av",
    "W 4 St-Wash Sq"
  ],
  "C": [
    "103 St",
    "116 St",
    "125 St",
    "135 St",
    "14 St",
    "145 St",
    "155 St",
    "163 St-Amsterdam Av",
    "168 St",
    "23 St",
    "34 St-Penn Station",
    "42 St-Port Authority Bus Terminal",
    "50 St",
    "59 St-Columbus Circle",
    "72 St",
    "81 St-Museum of Natural History",
    "86 St",
    "96 St",
    "Broadway Junction",
    "Canal St",
    "Cathedral Pkwy (110 St)",
    "Chambers St",
    "Clinton-Washington Avs",
    "Euclid Av",
    "Franklin Av",
    "Fulton St",
    "High St",
    "Hoyt-Schermerhorn Sts",
    "Jay St-MetroTech",
    "Kingston-Throop Avs",
    "Lafayette Av",
    "Liberty Av",
    "Nostrand Av",
    "Ralph Av",
    "Rockaway Av",
    "Shepherd Av",
    "Spring St",
    "Utica Av",
    "Van Siclen Av",
    "W 4 St-Wash Sq"
  ],
  "B": [
    "103 St",
    "116 St",
    "125 St",
    "135 St",
    "145 St",
    "155 St",
    "161 St-Yankee Stadium",
    "167 St",
    "170 St",
    "174-175 Sts",
    "182-183 Sts",
    "34 St-Herald Sq",
    "42 St-Bryant Pk",
    "47-50 Sts-Rockefeller Ctr",
    "59 St-Columbus Circle",
    "7 Av",
    "72 St",
    "81 St-Museum of Natural History",
    "86 St",
    "96 St",
    "Atlantic Av-Barclays Ctr",
    "Bedford Park Blvd",
    "Brighton Beach",
    "Broadway-Lafayette St",
    "Cathedral Pkwy (110 St)",
    "Church Av",
    "DeKalb Av",
    "Fordham Rd",
    "Grand St",
    "Kings Hwy",
    "Kingsbridge Rd",
    "Newkirk Plaza",
    "Prospect Park",
    "Sheepshead Bay",
    "Tremont Av",
    "W 4 St-Wash Sq"
  ],
  "D": [
    "125 St",
    "145 St",
    "155 St",
    "161 St-Yankee Stadium",
    "167 St",
    "170 St",
    "174-175 Sts",
    "18 Av",
    "182-183 Sts",
    "20 Av",
    "25 Av",
    "34 St-Herald Sq",
    "36 St",
    "42 St-Bryant Pk",
    "47-50 Sts-Rockefeller Ctr",
    "50 St",
    "55 St",
    "59 St-Columbus Circle",
    "62 St",
    "7 Av",
    "71 St",
    "79 St",
    "9 Av",
    "Atlantic Av-Barclays Ctr",
    "Bay 50 St",
    "Bay Pkwy",
    "Bedford Park Blvd",
    "Broadway-Lafayette St",
    "Coney Island-Stillwell Av",
    "Fordham Rd",
    "Fort Hamilton Pkwy",
    "Grand St",
    "Kingsbridge Rd",
    "Norwood-205 St",
    "Tremont Av",
    "W 4 St-Wash Sq"
  ],
  "4": [
    "125 St",
    "138 St-Grand Concourse",
    "14 St-Union Sq",
    "149 St-Grand Concourse",
    "161 St-Yankee Stadium",
    "167 St",
    "170 St",
    "176 St",
    "183 St",
    "59 St",
    "86 St",
    "Atlantic Av-Barclays Ctr",
    "Bedford Park Blvd-Lehman College",
    "Borough Hall",
    "Bowling Green",
    "Brooklyn Bridge-City Hall",
    "Burnside Av",
    "Crown Hts-Utica Av",
    "Fordham Rd",
    "Franklin Av-Medgar Evers College",
    "Fulton St",
    "Grand Central-42 St",
    "Kingsbridge Rd",
    "Mosholu Pkwy",
    "Mt Eden Av",
    "Nevins St",
    "Wall St",
    "Woodlawn"
  ],
  "5": [
    "125 St",
    "138 St-Grand Concourse",
    "14 St-Union Sq",
    "149 St-Grand Concourse",
    "174 St",
    "219 St",
    "225 St",
    "233 St",
    "3 Av-149 St",
    "59 St",
    "86 St",
    "Allerton Av",
    "Atlantic Av-Barclays Ctr",
    "Baychester Av",
    "Beverly Rd",
    "Borough Hall",
    "Bowling Green",
    "Bronx Park East",
    "Brooklyn Bridge-City Hall",
    "Burke Av",
    "Church Av",
    "E 180 St",
    "Eastchester-Dyre Av",
    "Flatbush Av-Brooklyn College",
    "Franklin Av-Medgar Evers College",
    "Freeman St",
    "Fulton St",
    "Grand Central-42 St",
    "Gun Hill Rd",
    "Intervale Av",
    "Jackson Av",
    "Morris Park",
    "Nereid Av",
    "Nevins St",
    "Newkirk Av-Little Haiti",
    "Pelham Pkwy",
    "President St-Medgar Evers College",
    "Prospect Av",
    "Simpson St",
    "Sterling St",
    "Wall St",
    "West Farms Sq-E Tremont Av",
    "Winthrop St"
  ],
  "N": [
    "14 St-Union Sq",
    "18 Av",
    "20 Av",
    "30 Av",
    "34 St-Herald Sq",
    "36 Av",
    "36 St",
    "39 Av-Dutch Kills",
    "49 St",
    "5 Av/59 St",
    "57 St-7 Av",
    "59 St",
    "8 Av",
    "86 St",
    "Astoria Blvd",
    "Astoria-Ditmars Blvd",
    "Atlantic Av-Barclays Ctr",
    "Avenue U",
    "Bay Pkwy",
    "Broadway",
    "Canal St",
    "Coney Island-Stillwell Av",
    "Fort Hamilton Pkwy",
    "Kings Hwy",
    "Lexington Av/59 St",
    "New Utrecht Av",
    "Queensboro Plaza",
    "Times Sq-42 St"
  ],
  "W": [
    "14 St-Union Sq",
    "23 St",
    "28 St",
    "30 Av",
    "34 St-Herald Sq",
    "36 Av",
    "39 Av-Dutch Kills",
    "49 St",
    "5 Av/59 St",
    "57 St-7 Av",
    "8 St-NYU",
    "Astoria Blvd",
    "Astoria-Ditmars Blvd",
    "Broadway",
    "Canal St",
    "City Hall",
    "Cortlandt St",
    "Lexington Av/59 St",
    "Prince St",
    "Queensboro Plaza",
    "Rector St",
    "Times Sq-42 St",
    "Whitehall St-South Ferry"
  ],
  "E": [
    "14 St",
    "23 St",
    "34 St-Penn Station",
    "42 St-Port Authority Bus Terminal",
    "5 Av/53 St",
    "50 St",
    "7 Av",
    "75 Av",
    "Briarwood",
    "Canal St",
    "Court Sq-23 St",
    "Forest Hills-71 Av",
    "Jackson Hts-Roosevelt Av",
    "Jamaica Center-Parsons/Archer",
    "Jamaica-Van Wyck",
    "Kew Gardens-Union Tpke",
    "Lexington Av/53 St",
    "Queens Plaza",
    "Spring St",
    "Sutphin Blvd-Archer Av-JFK Airport",
    "W 4 St-Wash Sq",
    "World Trade Center"
  ],
  "G": [
    "15 St-Prospect Park",
    "21 St",
    "4 Av-9 St",
    "7 Av",
    "Bedford-Nostrand Avs",
    "Bergen St",
    "Broadway",
    "Carroll St",
    "Church Av",
    "Classon Av",
    "Clinton-Washington Avs",
    "Court Sq",
    "Flushing Av",
    "Fort Hamilton Pkwy",
    "Fulton St",
    "Greenpoint Av",
    "Hoyt-Schermerhorn Sts",
    "Metropolitan Av",
    "Myrtle-Willoughby Avs",
    "Nassau Av",
    "Smith-9 Sts"
  ],
  "Q": [
    "14 St-Union Sq",
    "34 St-Herald Sq",
    "57 St-7 Av",
    "7 Av",
    "72 St",
    "86 St",
    "96 St",
    "Atlantic Av-Barclays Ctr",
    "Avenue H",
    "Avenue J",
    "Avenue M",
    "Avenue U",
    "Beverley Rd",
    "Brighton Beach",
    "Canal St",
    "Church Av",
    "Coney Island-Stillwell Av",
    "Cortelyou Rd",
    "DeKalb Av",
    "Kings Hwy",
    "Lexington Av/63 St",
    "Neck Rd",
    "Newkirk Plaza",
    "Ocean Pkwy",
    "Parkside Av",
    "Prospect Park",
    "Sheepshead Bay",
    "Times Sq-42 St",
    "W 8 St-NY Aquarium"
  ],
  "L": [
    "1 Av",
    "14 St-Union Sq",
    "3 Av",
    "6 Av",
    "8 Av",
    "Atlantic Av",
    "Bedford Av",
    "Broadway Junction",
    "Bushwick Av-Aberdeen St",
    "Canarsie-Rockaway Pkwy",
    "DeKalb Av",
    "East 105 St",
    "Graham Av",
    "Grand St",
    "Halsey St",
    "Jefferson St",
    "Livonia Av",
    "Lorimer St",
    "Montrose Av",
    "Morgan Av",
    "Myrtle-Wyckoff Avs",
    "New Lots Av",
    "Sutter Av",
    "Wilson Av"
  ]
};